### ISSUE TITLE
using opam

### ISSUE THREAD

**Issue by nverno** [vic/asdf-ocaml#11]
Hi, I just a question about using this plugin with opam (noob to ocaml in general).

After playing around with it for a bit, it seems opam will need to download the compiler version itself regardless of any compilers that have been downloaded previously through this plugin.  So, essentially, you get two versions of a compiler in order to use opam.  Is this expected? Or am I just configuring it wrong.

Thanks

**Comment by smorimoto** [comment]
Hi, are you asking about opam installed in a path like this?

`~/.asdf/installs/ocaml/[release]/[release]/bin`

If so, it's the intended behavior.

**Comment by nverno** [comment]
Yea, that;s opam path I was using, thanks!
