### ISSUE TITLE
Location of opam packages

### ISSUE THREAD

**Issue by schutm** [vic/asdf-ocaml#14]
Hi,

Currently asdf-ocaml initializes a switch in the asdf/releases directory during installation (the line ```./opam init --yes --root $install_path --comp $release``` in ```install```).

Does this mean that package are also stored in this directory and ['local projects/switches'](https://opam.ocaml.org/blog/opam-install-dir/#Handling-a-local-project) are not possible? If so I'd like to add ```OPAMROOT=$ASDF_INSTALL_PATH; export OPAMROOT``` to ```exec-env``` to ensure I don't have to set it manually. I can of course create a CR for this.
 
Best regards,
--Martin

**Comment by smorimoto** [comment]
Packages are installed in `~/.opam/default/bin`.

**Comment by schutm** [comment]
Thanks. I already found that. I'm still trying to grok the 'best' workflow for me.

**Comment by smorimoto** [comment]
@schutm If you have much time, could you check #15?
